-- ============================================================================
-- Aurora Academy LMS  ·  0002 — Identity & Access (RBAC)
-- ----------------------------------------------------------------------------
-- 8-role RBAC, profiles bound to Supabase auth.users, branches, guardianships,
-- and role-specific extension tables. Defines the RLS helper functions every
-- later migration relies on, then enables Row Level Security.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- roles  ·  the 8 platform roles
-- ---------------------------------------------------------------------------
create table public.roles (
  id          integer generated by default as identity primary key,
  key         text    not null unique,           -- machine key, used in code & RLS
  name        text    not null,                   -- human label (Uzbek)
  description text,
  level       smallint not null default 0,        -- privilege weight, higher = more
  is_staff    boolean  not null default false,    -- counts as internal staff
  created_at  timestamptz not null default now()
);
comment on table public.roles is 'Platform roles for RBAC (super_admin … guest).';

-- ---------------------------------------------------------------------------
-- permissions  ·  granular capabilities (optional fine-grained layer)
-- ---------------------------------------------------------------------------
create table public.permissions (
  id          integer generated by default as identity primary key,
  key         text not null unique,               -- e.g. 'course.create'
  description text,
  created_at  timestamptz not null default now()
);
comment on table public.permissions is 'Fine-grained capabilities assignable to roles.';

create table public.role_permissions (
  role_id       integer not null references public.roles(id) on delete cascade,
  permission_id integer not null references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);
comment on table public.role_permissions is 'Many-to-many: which permissions a role grants.';

-- ---------------------------------------------------------------------------
-- branches  ·  physical/virtual locations of the academy
-- ---------------------------------------------------------------------------
create table public.branches (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  slug       text unique,
  address    text,
  phone      text,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_branches_updated before update on public.branches
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- profiles  ·  1:1 with auth.users, public application identity
-- ---------------------------------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        citext unique,
  first_name   text,
  last_name    text,
  full_name    text generated always as
                 (btrim(coalesce(first_name, '') || ' ' || coalesce(last_name, ''))) stored,
  phone        text,
  avatar_url   text,
  gender       gender_type,
  birth_date   date,
  locale       text not null default 'uz',
  bio          text,
  status       user_status not null default 'active',
  branch_id    uuid references public.branches(id) on delete set null,
  last_seen_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
comment on table public.profiles is 'Application profile for each auth user.';
create index idx_profiles_branch on public.profiles(branch_id);
create index idx_profiles_status on public.profiles(status);
create index idx_profiles_name_trgm on public.profiles using gin (full_name gin_trgm_ops);
create trigger trg_profiles_updated before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- user_roles  ·  many-to-many; a user may be e.g. teacher AND parent
-- ---------------------------------------------------------------------------
create table public.user_roles (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid    not null references public.profiles(id) on delete cascade,
  role_id     integer not null references public.roles(id)    on delete cascade,
  branch_id   uuid    references public.branches(id) on delete set null,
  assigned_by uuid    references public.profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  unique (user_id, role_id)
);
create index idx_user_roles_user on public.user_roles(user_id);
create index idx_user_roles_role on public.user_roles(role_id);

-- ---------------------------------------------------------------------------
-- guardianships  ·  links parent/guardian profiles to student profiles
-- ---------------------------------------------------------------------------
create table public.guardianships (
  id          uuid primary key default gen_random_uuid(),
  student_id  uuid not null references public.profiles(id) on delete cascade,
  guardian_id uuid not null references public.profiles(id) on delete cascade,
  relation    guardian_relation not null default 'guardian',
  is_primary  boolean not null default false,
  created_at  timestamptz not null default now(),
  unique (student_id, guardian_id),
  check (student_id <> guardian_id)
);
create index idx_guardianships_guardian on public.guardianships(guardian_id);
create index idx_guardianships_student  on public.guardianships(student_id);

-- ---------------------------------------------------------------------------
-- teacher_profiles  ·  role-specific extension for teachers
-- ---------------------------------------------------------------------------
create table public.teacher_profiles (
  user_id          uuid primary key references public.profiles(id) on delete cascade,
  slug             text unique,
  headline         text,
  bio              text,
  experience_years smallint default 0,
  hourly_rate      numeric(12,2),
  rating           numeric(2,1) default 0 check (rating between 0 and 5),
  students_count   integer default 0,
  badges           text[] not null default '{}',
  subjects         text[] not null default '{}',
  is_featured      boolean not null default false,
  hired_at         date,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
comment on table public.teacher_profiles is 'Public teacher directory data.';
create trigger trg_teacher_profiles_updated before update on public.teacher_profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- student_profiles  ·  role-specific extension incl. gamification counters
-- ---------------------------------------------------------------------------
create table public.student_profiles (
  user_id        uuid primary key references public.profiles(id) on delete cascade,
  student_code   text unique,
  level          smallint not null default 1,
  xp             integer  not null default 0,
  coins          integer  not null default 0,
  current_streak smallint not null default 0,
  longest_streak smallint not null default 0,
  enrolled_at    date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
comment on table public.student_profiles is 'Per-student counters & gamification state.';
create trigger trg_student_profiles_updated before update on public.student_profiles
  for each row execute function public.set_updated_at();

-- ============================================================================
-- RLS HELPER FUNCTIONS
-- SECURITY DEFINER so they can read user_roles regardless of the caller's RLS.
-- Used throughout every later migration's policies.
-- ============================================================================
create or replace function public.has_role(p_role text)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.key = p_role
  );
$$;

create or replace function public.has_any_role(p_roles text[])
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = auth.uid()
      and r.key = any(p_roles)
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.has_any_role(array['super_admin', 'admin']);
$$;

-- Any internal staff member (admin, manager, teacher, assistant).
create or replace function public.is_staff()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.has_any_role(array['super_admin', 'admin', 'manager', 'teacher', 'assistant']);
$$;

create or replace function public.is_teacher()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select public.has_any_role(array['teacher', 'assistant']);
$$;

-- True when the current user is a guardian of the given student.
create or replace function public.is_guardian_of(p_student uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.guardianships g
    where g.student_id = p_student and g.guardian_id = auth.uid()
  );
$$;

-- ---------------------------------------------------------------------------
-- New-user hook: create a profile row when a Supabase auth user signs up.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name, phone)
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'first_name', ''),
    nullif(new.raw_user_meta_data ->> 'last_name', ''),
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.roles            enable row level security;
alter table public.permissions      enable row level security;
alter table public.role_permissions enable row level security;
alter table public.branches         enable row level security;
alter table public.profiles         enable row level security;
alter table public.user_roles       enable row level security;
alter table public.guardianships    enable row level security;
alter table public.teacher_profiles enable row level security;
alter table public.student_profiles enable row level security;

-- roles / permissions are reference data: readable by any authenticated user,
-- writable only by admins.
create policy roles_read   on public.roles            for select to authenticated using (true);
create policy roles_admin  on public.roles            for all    to authenticated using (public.is_admin()) with check (public.is_admin());
create policy perms_read   on public.permissions      for select to authenticated using (true);
create policy perms_admin  on public.permissions      for all    to authenticated using (public.is_admin()) with check (public.is_admin());
create policy rp_read      on public.role_permissions for select to authenticated using (true);
create policy rp_admin     on public.role_permissions for all    to authenticated using (public.is_admin()) with check (public.is_admin());

-- branches: visible to everyone (public site lists them); managed by admins.
create policy branches_read  on public.branches for select using (true);
create policy branches_admin on public.branches for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- profiles: a user sees & edits their own; staff & guardians can read; admins manage.
create policy profiles_select_self    on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_staff() or public.is_guardian_of(id));
create policy profiles_insert_self     on public.profiles for insert to authenticated
  with check (id = auth.uid());
create policy profiles_update_self     on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_admin_all       on public.profiles for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- user_roles: a user can see their own role assignments; only admins change them.
create policy user_roles_select on public.user_roles for select to authenticated
  using (user_id = auth.uid() or public.is_staff());
create policy user_roles_admin  on public.user_roles for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- guardianships: visible to the student, the guardian, or staff; admins manage.
create policy guardianships_select on public.guardianships for select to authenticated
  using (student_id = auth.uid() or guardian_id = auth.uid() or public.is_staff());
create policy guardianships_admin  on public.guardianships for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- teacher_profiles: PUBLIC read (marketing directory); self-edit or admin write.
create policy teacher_profiles_read   on public.teacher_profiles for select using (true);
create policy teacher_profiles_self   on public.teacher_profiles for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy teacher_profiles_admin  on public.teacher_profiles for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- student_profiles: student, their guardians, and staff can read; admin manages.
create policy student_profiles_select on public.student_profiles for select to authenticated
  using (user_id = auth.uid() or public.is_staff() or public.is_guardian_of(user_id));
create policy student_profiles_admin  on public.student_profiles for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
