-- ============================================================================
-- Aurora Academy LMS  ·  0003 — Education
-- ----------------------------------------------------------------------------
-- Course catalog (categories → courses → modules → lessons → materials) and
-- delivery (groups → enrollments, class_sessions → attendance, lesson_progress).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
create table public.categories (
  id         integer generated by default as identity primary key,
  slug       text not null unique,
  name       text not null,
  position   smallint not null default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- courses
-- ---------------------------------------------------------------------------
create table public.courses (
  id             uuid primary key default gen_random_uuid(),
  slug           text not null unique,
  title          text not null,
  subtitle       text,
  description    text,
  category_id    integer references public.categories(id) on delete set null,
  level          course_level not null default 'beginner',
  language       text not null default 'uz',
  duration_weeks smallint,
  lessons_count  smallint default 0,
  price          numeric(12,2) not null default 0,
  old_price      numeric(12,2),
  currency       text not null default 'UZS',
  rating         numeric(2,1) default 0 check (rating between 0 and 5),
  reviews_count  integer default 0,
  students_count integer default 0,
  teacher_id     uuid references public.profiles(id) on delete set null,  -- lead teacher
  cover_gradient text,                                  -- tailwind gradient classes
  cover_emoji    text,
  highlights     text[] not null default '{}',
  status         course_status not null default 'draft',
  is_popular     boolean not null default false,
  published_at   timestamptz,
  created_by     uuid references public.profiles(id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index idx_courses_category on public.courses(category_id);
create index idx_courses_teacher  on public.courses(teacher_id);
create index idx_courses_status   on public.courses(status);
create index idx_courses_title_trgm on public.courses using gin (title gin_trgm_ops);
create trigger trg_courses_updated before update on public.courses
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- course_modules
-- ---------------------------------------------------------------------------
create table public.course_modules (
  id         uuid primary key default gen_random_uuid(),
  course_id  uuid not null references public.courses(id) on delete cascade,
  title      text not null,
  summary    text,
  position   smallint not null default 0,
  created_at timestamptz not null default now()
);
create index idx_modules_course on public.course_modules(course_id);

-- ---------------------------------------------------------------------------
-- lessons
-- ---------------------------------------------------------------------------
create table public.lessons (
  id              uuid primary key default gen_random_uuid(),
  module_id       uuid not null references public.course_modules(id) on delete cascade,
  course_id       uuid not null references public.courses(id) on delete cascade,
  title           text not null,
  slug            text,
  content         text,
  video_url       text,
  duration_min    smallint,
  position        smallint not null default 0,
  is_free_preview boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index idx_lessons_module on public.lessons(module_id);
create index idx_lessons_course on public.lessons(course_id);
create trigger trg_lessons_updated before update on public.lessons
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- lesson_materials
-- ---------------------------------------------------------------------------
create table public.lesson_materials (
  id         uuid primary key default gen_random_uuid(),
  lesson_id  uuid not null references public.lessons(id) on delete cascade,
  title      text not null,
  type       material_type not null default 'file',
  url        text not null,
  size_bytes bigint,
  position   smallint not null default 0,
  created_at timestamptz not null default now()
);
create index idx_materials_lesson on public.lesson_materials(lesson_id);

-- ---------------------------------------------------------------------------
-- groups  ·  a cohort taking a course on a schedule
-- ---------------------------------------------------------------------------
create table public.groups (
  id         uuid primary key default gen_random_uuid(),
  course_id  uuid not null references public.courses(id) on delete restrict,
  name       text not null,
  teacher_id uuid references public.profiles(id) on delete set null,
  branch_id  uuid references public.branches(id) on delete set null,
  room       text,
  capacity   smallint default 20,
  mode       session_mode not null default 'offline',
  schedule   jsonb,                       -- e.g. {"days":["mon","wed","fri"],"time":"18:00"}
  start_date date,
  end_date   date,
  status     group_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_groups_course  on public.groups(course_id);
create index idx_groups_teacher on public.groups(teacher_id);
create index idx_groups_status  on public.groups(status);
create trigger trg_groups_updated before update on public.groups
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- enrollments  ·  a student's membership in a group/course
-- ---------------------------------------------------------------------------
create table public.enrollments (
  id           uuid primary key default gen_random_uuid(),
  student_id   uuid not null references public.profiles(id) on delete cascade,
  course_id    uuid not null references public.courses(id) on delete cascade,
  group_id     uuid references public.groups(id) on delete set null,
  status       enrollment_status not null default 'active',
  progress_pct numeric(5,2) not null default 0 check (progress_pct between 0 and 100),
  enrolled_at  timestamptz not null default now(),
  completed_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (student_id, group_id)
);
create index idx_enrollments_student on public.enrollments(student_id);
create index idx_enrollments_course  on public.enrollments(course_id);
create index idx_enrollments_group   on public.enrollments(group_id);
create trigger trg_enrollments_updated before update on public.enrollments
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- class_sessions  ·  a scheduled meeting of a group
-- ---------------------------------------------------------------------------
create table public.class_sessions (
  id          uuid primary key default gen_random_uuid(),
  group_id    uuid not null references public.groups(id) on delete cascade,
  lesson_id   uuid references public.lessons(id) on delete set null,
  title       text not null,
  starts_at   timestamptz not null,
  ends_at     timestamptz,
  room        text,
  mode        session_mode not null default 'offline',
  meeting_url text,                         -- Zoom / Meet link for online sessions
  status      session_status not null default 'scheduled',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_sessions_group on public.class_sessions(group_id);
create index idx_sessions_start on public.class_sessions(starts_at);
create trigger trg_sessions_updated before update on public.class_sessions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- attendance
-- ---------------------------------------------------------------------------
create table public.attendance (
  id         uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.class_sessions(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  status     attendance_status not null default 'present',
  note       text,
  marked_by  uuid references public.profiles(id) on delete set null,
  marked_at  timestamptz not null default now(),
  unique (session_id, student_id)
);
create index idx_attendance_student on public.attendance(student_id);
create index idx_attendance_session on public.attendance(session_id);

-- ---------------------------------------------------------------------------
-- lesson_progress  ·  per-student, per-lesson completion
-- ---------------------------------------------------------------------------
create table public.lesson_progress (
  id            uuid primary key default gen_random_uuid(),
  enrollment_id uuid not null references public.enrollments(id) on delete cascade,
  lesson_id     uuid not null references public.lessons(id) on delete cascade,
  status        progress_status not null default 'not_started',
  watch_seconds integer not null default 0,
  completed_at  timestamptz,
  updated_at    timestamptz not null default now(),
  unique (enrollment_id, lesson_id)
);
create index idx_progress_enrollment on public.lesson_progress(enrollment_id);
create trigger trg_progress_updated before update on public.lesson_progress
  for each row execute function public.set_updated_at();

-- ============================================================================
-- RLS HELPERS specific to education (defined now that the tables exist)
-- ============================================================================

-- Is the current user actively enrolled in a course?
create or replace function public.is_enrolled(p_course uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.enrollments e
    where e.course_id = p_course
      and e.student_id = auth.uid()
      and e.status in ('active', 'completed')
  );
$$;

-- Does the current user teach (lead) the given group?
create or replace function public.teaches_group(p_group uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.groups g
    where g.id = p_group and g.teacher_id = auth.uid()
  );
$$;

-- Does the current user teach the given course (as lead or via any group)?
create or replace function public.teaches_course(p_course uuid)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.courses c where c.id = p_course and c.teacher_id = auth.uid())
      or exists (select 1 from public.groups  g where g.course_id = p_course and g.teacher_id = auth.uid());
$$;

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.categories       enable row level security;
alter table public.courses           enable row level security;
alter table public.course_modules    enable row level security;
alter table public.lessons           enable row level security;
alter table public.lesson_materials  enable row level security;
alter table public.groups            enable row level security;
alter table public.enrollments       enable row level security;
alter table public.class_sessions    enable row level security;
alter table public.attendance        enable row level security;
alter table public.lesson_progress   enable row level security;

-- categories: public read, admin write
create policy categories_read  on public.categories for select using (true);
create policy categories_admin on public.categories for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- courses: published courses are public; staff see all; owner-teacher & admin write
create policy courses_read_public on public.courses for select
  using (status = 'published' or public.is_staff());
create policy courses_admin on public.courses for all to authenticated
  using (public.is_admin() or teacher_id = auth.uid())
  with check (public.is_admin() or teacher_id = auth.uid());

-- modules: readable when the parent course is published / enrolled / staff
create policy modules_read on public.course_modules for select using (
  public.is_staff()
  or public.teaches_course(course_id)
  or public.is_enrolled(course_id)
  or exists (select 1 from public.courses c where c.id = course_id and c.status = 'published')
);
create policy modules_admin on public.course_modules for all to authenticated
  using (public.is_admin() or public.teaches_course(course_id))
  with check (public.is_admin() or public.teaches_course(course_id));

-- lessons: free-preview & published-course metadata public; full access for
-- enrolled students, course teachers, and staff.
create policy lessons_read on public.lessons for select using (
  is_free_preview
  or public.is_staff()
  or public.teaches_course(course_id)
  or public.is_enrolled(course_id)
);
create policy lessons_admin on public.lessons for all to authenticated
  using (public.is_admin() or public.teaches_course(course_id))
  with check (public.is_admin() or public.teaches_course(course_id));

-- lesson_materials: follow the parent lesson's access (enrolled / teacher / staff)
create policy materials_read on public.lesson_materials for select using (
  public.is_staff()
  or exists (
    select 1 from public.lessons l
    where l.id = lesson_id
      and (l.is_free_preview or public.teaches_course(l.course_id) or public.is_enrolled(l.course_id))
  )
);
create policy materials_admin on public.lesson_materials for all to authenticated
  using (
    public.is_admin()
    or exists (select 1 from public.lessons l where l.id = lesson_id and public.teaches_course(l.course_id))
  )
  with check (
    public.is_admin()
    or exists (select 1 from public.lessons l where l.id = lesson_id and public.teaches_course(l.course_id))
  );

-- groups: staff & lead teacher; students see groups they belong to
create policy groups_read on public.groups for select to authenticated using (
  public.is_staff()
  or teacher_id = auth.uid()
  or exists (select 1 from public.enrollments e where e.group_id = id and e.student_id = auth.uid())
);
create policy groups_admin on public.groups for all to authenticated
  using (public.is_admin() or teacher_id = auth.uid())
  with check (public.is_admin() or teacher_id = auth.uid());

-- enrollments: student owns; group teacher & staff read; admin/teacher manage
create policy enrollments_select on public.enrollments for select to authenticated using (
  student_id = auth.uid()
  or public.is_staff()
  or public.teaches_group(group_id)
  or public.is_guardian_of(student_id)
);
create policy enrollments_admin on public.enrollments for all to authenticated
  using (public.is_admin() or public.teaches_group(group_id))
  with check (public.is_admin() or public.teaches_group(group_id));

-- class_sessions: enrolled students + group teacher + staff read; teacher/admin manage
create policy sessions_select on public.class_sessions for select to authenticated using (
  public.is_staff()
  or public.teaches_group(group_id)
  or exists (select 1 from public.enrollments e where e.group_id = group_id and e.student_id = auth.uid())
);
create policy sessions_admin on public.class_sessions for all to authenticated
  using (public.is_admin() or public.teaches_group(group_id))
  with check (public.is_admin() or public.teaches_group(group_id));

-- attendance: student sees own; group teacher & staff manage
create policy attendance_select on public.attendance for select to authenticated using (
  student_id = auth.uid()
  or public.is_staff()
  or public.is_guardian_of(student_id)
  or exists (
    select 1 from public.class_sessions s
    where s.id = session_id and public.teaches_group(s.group_id)
  )
);
create policy attendance_write on public.attendance for all to authenticated
  using (
    public.is_admin()
    or exists (select 1 from public.class_sessions s where s.id = session_id and public.teaches_group(s.group_id))
  )
  with check (
    public.is_admin()
    or exists (select 1 from public.class_sessions s where s.id = session_id and public.teaches_group(s.group_id))
  );

-- lesson_progress: the owning student writes; staff read
create policy progress_select on public.lesson_progress for select to authenticated using (
  public.is_staff()
  or exists (select 1 from public.enrollments e where e.id = enrollment_id and e.student_id = auth.uid())
);
create policy progress_write on public.lesson_progress for all to authenticated
  using (
    public.is_admin()
    or exists (select 1 from public.enrollments e where e.id = enrollment_id and e.student_id = auth.uid())
  )
  with check (
    public.is_admin()
    or exists (select 1 from public.enrollments e where e.id = enrollment_id and e.student_id = auth.uid())
  );
