-- ============================================================================
-- Aurora Academy LMS  ·  0005 — Finance
-- ----------------------------------------------------------------------------
-- Subscription/tariff plans, invoices, payments (Payme · Click · Uzum ·
-- Telegram · cash), and discount codes with redemption tracking.
--
-- NOTE: payment-provider webhooks should run with the Supabase service_role
-- key, which bypasses RLS. The policies below govern end-user (authenticated)
-- access only. Money-writing operations are restricted to admins/managers.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- plans  ·  pricing tiers (Standart / Pro / Premium)
-- ---------------------------------------------------------------------------
create table public.plans (
  id          integer generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  description text,
  price       numeric(12,2) not null default 0,
  period      billing_period not null default 'monthly',
  currency    text not null default 'UZS',
  features    text[] not null default '{}',
  cta_label   text,
  gradient    text,
  max_courses smallint,                    -- null = unlimited
  is_popular  boolean not null default false,
  is_active   boolean not null default true,
  position    smallint not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger trg_plans_updated before update on public.plans
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- invoices
-- ---------------------------------------------------------------------------
create table public.invoices (
  id         uuid primary key default gen_random_uuid(),
  number     text not null unique,         -- human-facing invoice number
  student_id uuid not null references public.profiles(id) on delete cascade,
  course_id  uuid references public.courses(id) on delete set null,
  group_id   uuid references public.groups(id) on delete set null,
  plan_id    integer references public.plans(id) on delete set null,
  amount     numeric(12,2) not null,
  currency   text not null default 'UZS',
  status     invoice_status not null default 'pending',
  due_date   date,
  issued_at  timestamptz not null default now(),
  paid_at    timestamptz,
  meta       jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_invoices_student on public.invoices(student_id);
create index idx_invoices_status  on public.invoices(status);
create trigger trg_invoices_updated before update on public.invoices
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- payments  ·  individual transactions against invoices
-- ---------------------------------------------------------------------------
create table public.payments (
  id              uuid primary key default gen_random_uuid(),
  invoice_id      uuid references public.invoices(id) on delete set null,
  student_id      uuid not null references public.profiles(id) on delete cascade,
  amount          numeric(12,2) not null,
  currency        text not null default 'UZS',
  provider        payment_provider not null,
  provider_txn_id text,
  status          payment_status not null default 'pending',
  paid_at         timestamptz,
  meta            jsonb not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index idx_payments_invoice on public.payments(invoice_id);
create index idx_payments_student on public.payments(student_id);
create index idx_payments_status  on public.payments(status);
create unique index uq_payments_provider_txn
  on public.payments(provider, provider_txn_id)
  where provider_txn_id is not null;
create trigger trg_payments_updated before update on public.payments
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- discounts  ·  promo / coupon codes
-- ---------------------------------------------------------------------------
create table public.discounts (
  id          uuid primary key default gen_random_uuid(),
  code        citext not null unique,
  description text,
  type        discount_type not null default 'percent',
  value       numeric(12,2) not null,       -- percent (0-100) or fixed amount
  max_uses    integer,                       -- null = unlimited
  used_count  integer not null default 0,
  course_id   uuid references public.courses(id) on delete cascade,
  valid_from  timestamptz,
  valid_to    timestamptz,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);
create index idx_discounts_active on public.discounts(is_active);

-- ---------------------------------------------------------------------------
-- discount_redemptions
-- ---------------------------------------------------------------------------
create table public.discount_redemptions (
  id          uuid primary key default gen_random_uuid(),
  discount_id uuid not null references public.discounts(id) on delete cascade,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  invoice_id  uuid references public.invoices(id) on delete set null,
  amount      numeric(12,2),
  redeemed_at timestamptz not null default now(),
  unique (discount_id, student_id)
);
create index idx_redemptions_student on public.discount_redemptions(student_id);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.plans                enable row level security;
alter table public.invoices             enable row level security;
alter table public.payments             enable row level security;
alter table public.discounts            enable row level security;
alter table public.discount_redemptions enable row level security;

-- plans: active plans are public (pricing page); admins manage
create policy plans_read  on public.plans for select using (is_active or public.is_staff());
create policy plans_admin on public.plans for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- invoices: student & guardian read own; admins/managers manage
create policy invoices_select on public.invoices for select to authenticated using (
  student_id = auth.uid() or public.is_guardian_of(student_id)
  or public.has_any_role(array['super_admin','admin','manager'])
);
create policy invoices_admin on public.invoices for all to authenticated
  using (public.has_any_role(array['super_admin','admin','manager']))
  with check (public.has_any_role(array['super_admin','admin','manager']));

-- payments: student & guardian read own; admins/managers manage (webhooks use service_role)
create policy payments_select on public.payments for select to authenticated using (
  student_id = auth.uid() or public.is_guardian_of(student_id)
  or public.has_any_role(array['super_admin','admin','manager'])
);
create policy payments_admin on public.payments for all to authenticated
  using (public.has_any_role(array['super_admin','admin','manager']))
  with check (public.has_any_role(array['super_admin','admin','manager']));

-- discounts: staff-only visibility (codes are validated server-side); admin manage
create policy discounts_staff on public.discounts for select to authenticated using (public.is_staff());
create policy discounts_admin on public.discounts for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- discount_redemptions: student reads own; staff read; admins/managers manage
create policy redemptions_select on public.discount_redemptions for select to authenticated using (
  student_id = auth.uid() or public.has_any_role(array['super_admin','admin','manager'])
);
create policy redemptions_admin on public.discount_redemptions for all to authenticated
  using (public.has_any_role(array['super_admin','admin','manager']))
  with check (public.has_any_role(array['super_admin','admin','manager']));
