-- ============================================================================
-- Aurora Academy LMS  ·  0007 — Gamification
-- ----------------------------------------------------------------------------
-- Levels (XP thresholds), achievements & per-user unlocks, and an append-only
-- XP/coin ledger. Aggregate counters (xp, coins, level, streaks) live on
-- public.student_profiles (migration 0002); this layer is the source of truth
-- and audit trail behind those counters.
--
-- NOTE: awarding XP / unlocking achievements is done server-side (triggers,
-- edge functions, or SECURITY DEFINER RPCs running as service_role). End users
-- get read-only access to their own progress; admins manage definitions.
-- ============================================================================

-- Gamification-local enums (kept here so 0001 stays domain-agnostic).
create type achievement_category as enum ('learning', 'streak', 'social', 'milestone', 'special');
create type achievement_rarity   as enum ('common', 'rare', 'epic', 'legendary');
create type xp_reason            as enum ('lesson', 'assignment', 'test', 'streak', 'achievement', 'enrollment', 'bonus', 'manual', 'penalty');

-- ---------------------------------------------------------------------------
-- levels  ·  XP thresholds & titles (reference data)
-- ---------------------------------------------------------------------------
create table public.levels (
  level      smallint primary key,
  min_xp     integer not null,             -- cumulative XP required to reach this level
  title      text not null,
  perks      text[] not null default '{}',
  badge      text,                          -- emoji / icon key
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- achievements  ·  badge definitions
-- ---------------------------------------------------------------------------
create table public.achievements (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,         -- machine key, used by award logic
  name        text not null,
  description text,
  icon        text,                          -- emoji / icon key
  category    achievement_category not null default 'milestone',
  rarity      achievement_rarity   not null default 'common',
  xp_reward   integer not null default 0,
  coin_reward integer not null default 0,
  criteria    jsonb   not null default '{}', -- machine-readable unlock rule
  is_active   boolean not null default true,
  is_secret   boolean not null default false,
  position    smallint not null default 0,
  created_at  timestamptz not null default now()
);
create index idx_achievements_active on public.achievements(is_active);

-- ---------------------------------------------------------------------------
-- user_achievements  ·  unlocks & progress
-- ---------------------------------------------------------------------------
create table public.user_achievements (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles(id) on delete cascade,
  achievement_id uuid not null references public.achievements(id) on delete cascade,
  progress       numeric(5,2) not null default 100 check (progress between 0 and 100),
  is_unlocked    boolean not null default true,
  unlocked_at    timestamptz not null default now(),
  unique (user_id, achievement_id)
);
create index idx_user_achievements_user on public.user_achievements(user_id);

-- ---------------------------------------------------------------------------
-- xp_ledger  ·  append-only XP & coin movements (audit trail behind counters)
-- ---------------------------------------------------------------------------
create table public.xp_ledger (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  reason      xp_reason not null default 'manual',
  xp_delta    integer not null default 0,
  coin_delta  integer not null default 0,
  source_type text,                          -- 'lesson' | 'assignment' | 'test' | 'achievement' | ...
  source_id   uuid,
  note        text,
  awarded_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index idx_xp_ledger_user    on public.xp_ledger(user_id);
create index idx_xp_ledger_created on public.xp_ledger(created_at);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.levels            enable row level security;
alter table public.achievements      enable row level security;
alter table public.user_achievements enable row level security;
alter table public.xp_ledger         enable row level security;

-- levels & achievements: public catalog (powers profile/marketing UI); admin writes.
create policy levels_read  on public.levels for select using (true);
create policy levels_admin on public.levels for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- secret achievements are hidden until the viewer has unlocked them (or is staff).
create policy achievements_read on public.achievements for select using (
  (is_active and not is_secret)
  or public.is_staff()
  or exists (
    select 1 from public.user_achievements ua
    where ua.achievement_id = achievements.id and ua.user_id = auth.uid()
  )
);
create policy achievements_admin on public.achievements for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- user_achievements: user & guardian & staff read; admin manages (awards via service_role).
create policy user_achievements_select on public.user_achievements for select to authenticated using (
  user_id = auth.uid() or public.is_staff() or public.is_guardian_of(user_id)
);
create policy user_achievements_admin on public.user_achievements for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- xp_ledger: user & guardian & staff read; admin manages (awards via service_role).
create policy xp_ledger_select on public.xp_ledger for select to authenticated using (
  user_id = auth.uid() or public.is_staff() or public.is_guardian_of(user_id)
);
create policy xp_ledger_admin on public.xp_ledger for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
