-- ============================================================================
-- Aurora Academy LMS  ·  0008 — System & CMS
-- ----------------------------------------------------------------------------
-- Blog/CMS (categories → posts), key-value settings (feature flags folded in
-- here), an app-level file registry, third-party integrations, lead capture
-- (contact messages & course applications), and an append-only audit log.
--
-- NOTE: integration secrets do NOT live here — store API keys/tokens in
-- Supabase Vault. The `config` column holds non-secret configuration only.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- blog_categories
-- ---------------------------------------------------------------------------
create table public.blog_categories (
  id         integer generated by default as identity primary key,
  slug       text not null unique,
  name       text not null,
  position   smallint not null default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- blog_posts
-- ---------------------------------------------------------------------------
create table public.blog_posts (
  id             uuid primary key default gen_random_uuid(),
  slug           text not null unique,
  title          text not null,
  excerpt        text,
  body           text,
  category_id    integer references public.blog_categories(id) on delete set null,
  author_id      uuid references public.profiles(id) on delete set null,
  cover_gradient text,
  cover_emoji    text,
  read_time_min  smallint,
  tags           text[] not null default '{}',
  status         post_status not null default 'draft',
  views_count    integer not null default 0,
  published_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index idx_blog_posts_status    on public.blog_posts(status);
create index idx_blog_posts_category  on public.blog_posts(category_id);
create index idx_blog_posts_published on public.blog_posts(published_at desc);
create index idx_blog_posts_title_trgm on public.blog_posts using gin (title gin_trgm_ops);
create trigger trg_blog_posts_updated before update on public.blog_posts
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- settings  ·  key-value app config; feature flags live here (group = 'features')
-- ---------------------------------------------------------------------------
create table public.settings (
  key         text primary key,             -- e.g. 'site.title', 'features.ai_tutor'
  value       jsonb not null default '{}',
  group_name  text not null default 'general',
  description text,
  is_public   boolean not null default false,  -- public settings readable anonymously
  updated_by  uuid references public.profiles(id) on delete set null,
  updated_at  timestamptz not null default now()
);
create index idx_settings_group on public.settings(group_name);
create trigger trg_settings_updated before update on public.settings
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- files  ·  app-level metadata for objects stored in Supabase Storage
-- ---------------------------------------------------------------------------
create table public.files (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid references public.profiles(id) on delete set null,
  bucket     text not null default 'public',
  path       text not null,                 -- storage object path
  url        text,
  name       text,
  mime_type  text,
  size_bytes bigint,
  kind       text,                          -- 'avatar' | 'material' | 'submission' | 'certificate' | 'blog' | ...
  is_public  boolean not null default false,
  created_at timestamptz not null default now()
);
create index idx_files_owner on public.files(owner_id);
create index idx_files_kind  on public.files(kind);

-- ---------------------------------------------------------------------------
-- integrations  ·  third-party connections (Payme, Click, Zoom, Telegram, ...)
-- ---------------------------------------------------------------------------
create table public.integrations (
  id           integer generated by default as identity primary key,
  provider     integration_provider not null unique,
  name         text not null,
  status       integration_status not null default 'disconnected',
  is_enabled   boolean not null default false,
  config       jsonb not null default '{}', -- NON-SECRET config only (secrets → Vault)
  last_sync_at timestamptz,
  connected_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create trigger trg_integrations_updated before update on public.integrations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- contact_messages  ·  public "contact us" form submissions (lead capture)
-- ---------------------------------------------------------------------------
create table public.contact_messages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       citext,
  phone       text,
  subject     text,
  message     text not null,
  source      text,                          -- which page/form
  status      text not null default 'new',   -- new | read | replied | archived
  handled_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index idx_contact_messages_status on public.contact_messages(status);

-- ---------------------------------------------------------------------------
-- course_applications  ·  prospective-student applications (admin "Applications")
-- ---------------------------------------------------------------------------
create table public.course_applications (
  id          uuid primary key default gen_random_uuid(),
  course_id   uuid references public.courses(id) on delete set null,
  branch_id   uuid references public.branches(id) on delete set null,
  full_name   text not null,
  phone       text not null,
  email       citext,
  message     text,
  status      text not null default 'new',   -- new | contacted | enrolled | rejected
  assigned_to uuid references public.profiles(id) on delete set null,
  student_id  uuid references public.profiles(id) on delete set null,  -- set once enrolled
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index idx_course_applications_status on public.course_applications(status);
create index idx_course_applications_course on public.course_applications(course_id);
create trigger trg_course_applications_updated before update on public.course_applications
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- audit_logs  ·  append-only record of sensitive actions
-- ---------------------------------------------------------------------------
create table public.audit_logs (
  id          bigint generated by default as identity primary key,
  actor_id    uuid references public.profiles(id) on delete set null,
  action      text not null,                 -- 'create' | 'update' | 'delete' | 'login' | ...
  entity_type text,                          -- 'invoice' | 'enrollment' | 'profile' | ...
  entity_id   text,                          -- uuid/int as text (heterogeneous keys)
  summary     text,
  diff        jsonb,                         -- {before, after}
  ip          inet,
  user_agent  text,
  created_at  timestamptz not null default now()
);
create index idx_audit_actor   on public.audit_logs(actor_id);
create index idx_audit_entity  on public.audit_logs(entity_type, entity_id);
create index idx_audit_created on public.audit_logs(created_at);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.blog_categories      enable row level security;
alter table public.blog_posts           enable row level security;
alter table public.settings             enable row level security;
alter table public.files                enable row level security;
alter table public.integrations         enable row level security;
alter table public.contact_messages     enable row level security;
alter table public.course_applications  enable row level security;
alter table public.audit_logs           enable row level security;

-- blog: published content is public; categories public; staff author, admin manage.
create policy blog_categories_read  on public.blog_categories for select using (true);
create policy blog_categories_admin on public.blog_categories for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy blog_posts_read on public.blog_posts for select
  using (status = 'published' or public.is_staff());
create policy blog_posts_admin on public.blog_posts for all to authenticated
  using (public.is_admin() or author_id = auth.uid())
  with check (public.is_admin() or author_id = auth.uid());

-- settings: public flag exposes to anon (e.g. site title, enabled features); admin writes.
create policy settings_read_public on public.settings for select
  using (is_public or public.is_staff());
create policy settings_admin on public.settings for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- files: owner & staff read; public files readable by anyone; owner/admin write.
create policy files_select on public.files for select
  using (is_public or owner_id = auth.uid() or public.is_staff());
create policy files_owner_write on public.files for all to authenticated
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());

-- integrations: admin-only (configuration surface).
create policy integrations_admin on public.integrations for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- contact_messages: anyone (incl. anonymous) may submit; staff read; admin manage.
create policy contact_messages_insert on public.contact_messages for insert to anon, authenticated
  with check (true);
create policy contact_messages_select on public.contact_messages for select to authenticated
  using (public.is_staff());
create policy contact_messages_admin on public.contact_messages for all to authenticated
  using (public.has_any_role(array['super_admin','admin','manager']))
  with check (public.has_any_role(array['super_admin','admin','manager']));

-- course_applications: anyone may apply; staff read; managers/admins manage.
create policy course_applications_insert on public.course_applications for insert to anon, authenticated
  with check (true);
create policy course_applications_select on public.course_applications for select to authenticated
  using (public.is_staff());
create policy course_applications_admin on public.course_applications for all to authenticated
  using (public.has_any_role(array['super_admin','admin','manager']))
  with check (public.has_any_role(array['super_admin','admin','manager']));

-- audit_logs: admins read; no client writes (written by service_role / triggers).
create policy audit_logs_admin_read on public.audit_logs for select to authenticated
  using (public.is_admin());
